# general settings
name: train_HAT_SRx1_finetune_from_NTIRE
model_type: HATModel
scale: 1
num_gpu: auto
manual_seed: 0
find_unused_parameters: true
# dataset and data loader settings
datasets:
  train:
    name: NtireImage
    type: NtireImageDataset
    dataroot_gt: /opt/data/private/gzy/dataset/synthetic_train/HR
    dataroot_lq: datasets/LR
    # dataroot_diff: /opt/data/private/gzy/dataset/competition_train/synthetic_train_SR/LR_enhance
    dataroot_diff: datasets/LR-en-new
    # meta_info_file: hat/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val_1:
    name: NtireImage
    type: NtireImageDataset
    dataroot_gt: /opt/data/private/gzy/dataset/synthetic_train/HR
    dataroot_lq: datasets/LR
    # dataroot_diff: /opt/data/private/gzy/dataset/competition_train/synthetic_train_SR/LR_enhance
    dataroot_diff: datasets/LR-en-new
    io_backend:
      type: disk

  # val_2:
  #   name: Set14
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/Set14/GTmod3
  #   dataroot_lq: ./datasets/Set14/LRbicx3
  #   io_backend:
  #     type: disk

  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/urban100/GTmod3
  #   dataroot_lq: ./datasets/urban100/LRbicx3
  #   io_backend:
  #     type: disk


# network structures
network_g:
  type: PostProcess_V2
  upscale: 1
  in_chans: 3
  img_size: 64
  window_size: 8
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [1]
  embed_dim: 144
  num_heads: [6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: experiments/train_HAT_SRx1_finetune_from_NTIRE/training_states/20000.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 240000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # # losses
  # pixel_opt:
  #   type: L1Loss
  #   loss_weight: 1.0
  #   reduction: mean

  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 1e6
  save_img: False
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
